[project]
name = "SBI-for-Diffusion-Models"
version = "0.1.0"
description = ""
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/sbi_for_diffusion_models"]